version: '3'
services:
    nginx:
        build:
            context: "./docker/nginx"
        depends_on:
            -   php8
        volumes:
            - ./docker/nginx/sites:/etc/nginx/sites-available
            - ./app/:/var/www/
        ports:
            - "80:80"
        networks:
            - sail
    php8:
        build:
            context: "docker/php8"
        volumes:
            - ./app:/var/www
        networks:
            - sail
        expose:
            - "9000"
    mysql:
        image: mysql:8.0-oracle
        environment:
            MYSQL_USER: ${MYSQL_USER:-admin}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - ${MYSQL_HOST_PORT:-3306}:3306
        networks:
            - sail
        restart: unless-stopped


    pgsql:
        image: 'postgres:14'
        ports:
            - '${POSTGRES_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${POSTGRES_PASSWORD:-secret}'
            POSTGRES_USER: '${POSTGRES_USERNAME:-postgres}'
            POSTGRES_PASSWORD: '${POSTGRES_ROOT_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local